name: Test CI

on:
    push:
        branches:
            - workflows
    workflow_dispatch:

jobs:
    test_ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Test SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Testing SSH connection..."
                      echo "Successfully connected to the VPS!"
    build_and_deploy:
        runs-on: ubuntu-latest
        needs: test_ssh
        steps:
            - name: Build new version (Install Yarn + PM2)
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Installing dependencies and building..."

                      # Ensure Node.js and npm are available
                      if ! command -v node >/dev/null 2>&1; then
                        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                        sudo apt-get install -y nodejs
                      fi

                      # Ensure Yarn is installed
                      if ! command -v yarn >/dev/null 2>&1; then
                        npm install -g yarn
                      fi



                      # Build project
                      pm2 stop cashlog || exit 1
                      cd cashlog-nextjs
                      git checkout main
                      git pull origin main
                      yarn install || exit 1
                      yarn build || exit 1
                      pm2 restart cashlog
                      echo "Build completed successfully!"
                      exit 0
    notify_success:
        runs-on: ubuntu-latest
        needs: build_and_deploy
        steps:
            - name: Notify success
              if: ${{ success() }}
              run: echo "✅ Cashlog deployment completed successfully!"

            - name: Notify failure
              if: ${{ failure() }}
              run: echo "❌ Cashlog deployment failed!"
