name: Test CI

on:
    push:
        branches:
            - workflows
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Test SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Testing SSH connection..."
                      echo "Successfully connected to the VPS!"

            - name: Stop Cashlog on PM2
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Stopping Cashlog on PM2..."
                      cd cashlog-nextjs
                      pm2 stop cashlog || exit 1
                      echo "Cashlog stopped successfully!"

            - name: Build new version
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Building new version..."

                      cd cashlog-nextjs
                      git checkout main
                      git pull origin main

                      if ! command -v node >/dev/null 2>&1; then
                        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                        sudo apt-get install -y nodejs
                      fi

                      if ! command -v yarn >/dev/null 2>&1; then
                        npm install -g yarn
                      fi

                      yarn install
                      yarn build
                      echo "Build completed successfully!"

            - name: Restart Cashlog on PM2
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Restarting Cashlog on PM2..."
                      pm2 start cashlog
                      echo "Cashlog restarted successfully!"

            - name: Notify success
              if: ${{ success() }}
              run: echo "Cashlog deployment completed successfully!"; exit 0

            - name: Notify failure
              if: ${{ failure() }}
              run: echo "Cashlog deployment failed!"; exit 1
