name: Test CI

on:
    push:
        branches:
            - workflows
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup SSH agent
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  # passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  # key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: whoami

            - name: Add SSH host to known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

            - name: SSH to VPS
              run: |
                  ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected to VPS!"
