name: Test CI

on:
    push:
        branches:
            - workflows
    workflow_dispatch:

jobs:
    test_ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Test SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Testing SSH connection..."
                      echo "Successfully connected to the VPS!"
    build_and_deploy:
        runs-on: ubuntu-latest
        needs: test_ssh
        steps:
            - name: Build new version (Install Yarn + PM2)
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |
                      echo "Installing dependencies and building..."

                      # Ensure Node.js and npm are available
                      if ! command -v node >/dev/null 2>&1; then
                        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
                        sudo apt-get install -y nodejs
                      fi

                      # Ensure Yarn is installed
                      if ! command -v yarn >/dev/null 2>&1; then
                        npm install -g yarn
                      fi

                      # Ensure PM2 is installed
                      if ! command -v pm2 >/dev/null 2>&1; then
                        npm install -g pm2
                      fi

                      # Build project
                      pm2 stop cashlog || exit 1
                      cd cashlog-nextjs
                      git checkout main
                      git pull origin main
                      yarn install || exit 1
                      yarn build || exit 1
                      pm2 restart cashlog
                      echo "Build completed successfully!"
                      exit 0
    # update package.json version
    update_version:
        runs-on: ubuntu-latest
        needs: build_and_deploy
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Determine version bump type
              id: get_bump
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script: |

                      echo "commit_message<<EOF" >> $GITHUB_OUTPUT
                      echo "${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
                      echo "EOF" >> $GITHUB_OUTPUT

                      bump="patch"
                      msg="${{ github.event.head_commit.message }}"
                      if echo "$msg" | grep -i "major"; then
                          bump="major"
                      elif echo "$msg" | grep -i "minor"; then
                          bump="minor"
                      else bump="patch"
                      fi

                      echo "Updating package.json version..."
                      cd cashlog-nextjs
                      npm version $bump -m "Auto Bump version to %s"
                      git config --global user.email "github-actions[bot]@users.noreply.github.com"
                      git config --global user.name "github-actions[bot]"
                      git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
                      git push origin main
                      echo "Version updated successfully!"
